name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - run: npm ci
    
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          install: false
        env:
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-output
          path: |
            /cypress/videos
            /cypress/screenshots
