name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  e2e:
    runs-on: ubuntu-latest
    # container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm start
        env:
          CYPRESS_AZURE_TENANT_ID: ${{ secrets.CYPRESS_AZURE_TENANT_ID }}
          CYPRESS_AZURE_CLIENT_ID: ${{ secrets.CYPRESS_AZURE_CLIENT_ID }}
          CYPRESS_AZURE_CLIENT_SECRET: ${{ secrets.CYPRESS_AZURE_CLIENT_SECRET }}
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
